#!/bin/bash

set -e

__dirname="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
bin="${__dirname}/../node_modules/.bin"

echo "Compiling with Typescript"
"${bin}/tsc" -p . || exit 1 &
"${bin}/tsc" -p tsconfig.cli.json || exit 1 &

wait

echo "Bundling bot with rollup"
"${bin}/rollup" -c || exit 1

echo "If there is a warning above saying \"Entry module 'lib/index.js' is implicitly using 'default' export mode\", you can dismiss it."

wait

chmod --verbose +x bot.mjs

echo "Done"
