#!/bin/bash

echo "Compiling with Typescript"
./node_modules/.bin/tsc -p . || exit 1 &
./node_modules/.bin/tsc -p tsconfig.cli.json || exit 1 &

wait

echo "Bundling bot with rollup"
./node_modules/.bin/rollup -c || exit 1

echo "If there is a warning above saying \"Entry module 'lib/index.js' is implicitly using 'default' export mode\", you can dismiss it."

wait

chmod --verbose +x bot.mjs

echo "Done"
