#!/bin/bash

git checkout release

git add --force lib

git add --force cli/

rm -rfv ./test .eslintignore .eslintrc.json tsconfig.json tsconfig.cli.json yarn.lock docs assets

version="1.0.0"

git commit -asm"Release for version $version"

git push -uf origin release
