#!/bin/sh

version="$(grep version package.json | awk '{print $2}' | tr -d \" | tr -d ,)"

# Config git
git config --local user.email "luke.zhang2004dev@gmail.com"
git config --local user.name "Luke-zhang-04"

# Add JS files for distribution
git add --force bot.js
git add --force cli/

# Remove unecessary files
rm -rfv .github assets cli/*.ts lib test .babelrc.js .editorconfig .eslintignore .eslitnrc .gitattributes config.yml rollup.config.js tsconfig.cli.json tsconfig.json yarn.lock

# Commit
git commit -am "Release for version $version"
