#!/bin/sh

if [ "$1" = "--dev" ]||[ "$1" = "-d" ]; then
    echo "Compiling for development"
    ./node_modules/.bin/tsc

    echo "Starting up!"
    ./node_modules/.bin/nodemon --watch lib lib
else
    echo "Starting up!"
    node bot.js
fi
