#!/bin/sh

__dirname="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
bin="${__dirname}/node_modules/.bin"

"$bin/rollup" -c

"$bin/sass" ./style.scss ./style.css --style=compressed --embed-source-map
