name: Node.js CI (skip Google Sheets API)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["12.x", "14.x"]

    name: Build and test Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: ./node_modules/.bin/eslint src/"{*,**/*}"."{ts,tsx}" --max-warnings=0

      - name: Prettier
        run: ./node_modules/.bin/prettier src/ --check

      - name: build
        run: ./scripts/compile

      - name: test
        run: NODE_ENV=test ./node_modules/.bin/mocha --timeout 10000 --no-googlesheets --exit
