name: Node.js CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["12.x", "14.x"]

    name: Build and test Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Setup node ${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: lint
        run: ./node_modules/.bin/eslint src/**/*.ts

      - name: build
        run: ./scripts/compile

      - name: test
        run: NODE_ENV=test APIKEY=${{ secrets.APIKEY }} ./node_modules/.bin/mocha --timeout 10000
