name: Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Release

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build bot
        run: ./scripts/compile

      - name: Commit files
        run: ./scripts/release

      - name: Remove scripts
        run: rm -rfv scripts

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "release"
          force: true
